name: run main.py

on:
  schedule:
    # This cron expression runs the workflow every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-xml:
    runs-on: ubuntu-latest  # Docker runs on a Linux environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: setup python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: |
        python main.py  # Ensure the script name is correct

    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add feed.xml
        git commit -m "Daily update of feed.xml"
        git push
