name: run main.py

on:
  schedule:
    # This cron expression runs the workflow every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  update-xml:
    runs-on: ubuntu-latest  # Docker runs on a Linux environment

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.7'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Script
      run: |
        python main.py  # Ensure the script name is correct

    - name: Commit and push changes
      env:
        TOKEN: ${{ secrets.GH_TOKEN }}  # Ensure GH_TOKEN is set as a repository secret
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        git pull origin main --rebase  # Pull the latest changes and rebase
        git add feed.xml
        git commit -m "Daily update of feed.xml"
        git push https://x-access-token:${TOKEN}@github.com/srdobolo/XML-Feed-From-jobPosting-Strutured-Data.git
