name: Run Script Daily

on:
  schedule:
    # This cron expression runs the workflow every 5 minutes
    - cron: '*/5 * * * *'

jobs:
  update-xml:
    runs-on: ubuntu-latest  # Running on Linux since you're using Docker

    container:
      image: python:3.6  # Use a Docker image with Python 3.6 pre-installed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Exclude pywin32 (Windows-only package) and install remaining dependencies
        sed '/pywin32/d' requirements.txt > requirements_linux.txt
        pip install -r requirements_linux.txt

    - name: Run Script
      run: |
        python your_script.py  # Ensure the script name is correct

    - name: Commit and push changes
      run: |
        git config --global user.name "Your Name"
        git config --global user.email "your-email@example.com"
        git add feed.xml
        git commit -m "Daily update of feed.xml"
        git push
